### ISSUE TITLE
abort in onResouceRequest

### ISSUE THREAD

**Issue by royalgarter** [baudehlo/node-phantom-simple#7] opened 2013-08-21 14:39 UTC
Hi all,

I want to abort some ads resource on request but cannot call the abort() function.
Error: TypeError: Object #<Object> has no method 'abort'

Can someone give me an example that how to do it in page.onResourceRequested or do I miss understand something ?

**Comment by puzrin** [comment] 2015-07-09 19:51
IMHO you can install your handler in phantom namespace via `setFn`, and have access to `.abort` there.

Can we close this?

**Comment by puzrin** [comment] 2015-08-01 23:00
Closing - timed out. Seems nobody really need this. Use `setFn` if needed.

**Closed by puzrin** 2015-08-01 23:00 UTC
Labels: Need more info

**Comment by maZahaca** [comment] 2015-11-28 22:29
This is not working with Phantomjs 2. Could you provide an example?

**Comment by shawncreed** [comment] 2017-10-15 17:21
@puzrin The problem is that when running via setFn, the request.abort() is available, however the function isn't actually executed when a resource is requested, so it's kind of useless.

**Comment by puzrin** [comment] 2017-10-15 17:24
@shawncreed it worth to create new issue with details, this one is outdated IMHO.
