### ISSUE TITLE
'On confirm' event is not responding to callback return value

### ISSUE THREAD

**Issue by johntitus** [baudehlo/node-phantom-simple#71] opened 2015-08-26 19:44 UTC
Pushing an issue in node-horseman further down the chain...https://github.com/johntitus/node-horseman/issues/41.

The approach that @Unlearn is using seems fine. I don't see any obvious javascript errors.  So I tried to determine if this is a node-phantom-simple error or a node-horseman issue.  

I've recreated the test script for node-phantom-simple, below, and I'm getting the same kind of error. I don't know if this is 
a) me and @unlearn doing something wrong
b) an error in node-phantom-simple
c) an error in phantom

Any help is appreciated.

```js
var driver = require('node-phantom-simple');

driver.create( function (err, browser) {
    browser.createPage(function (err, page) {
        page.onConfirm = function( msg ){
            console.log('Confirm message: %s', msg);
            return true;
        }
        page.onLoadFinished = function(status) {
            console.log('Status %s', status);
        }
        page.onConsoleMessage = function( msg, lineNumber, sourceId ) {
            console.log('Console: %s, %s, %s', msg, lineNumber, sourceId);
        }
        page.open('file:///tmp/confirm/confirm.html', function (err,status) {
            console.log("opened site? ", status);
            page.evaluate( function() {           
                var element = document.querySelector('a#confirm');
                var event = document.createEvent('MouseEvent');
                event.initEvent('click', true, true);
                element.dispatchEvent(event);
            }, function(){
                browser.exit();
            });
        });
    });
});
```

**Comment by puzrin** [comment] 2015-08-26 20:18
https://github.com/baudehlo/node-phantom-simple/blob/master/bridge.js#L138

As far as i see, existing implementation does not supports returning data from handlers.

**Comment by puzrin** [comment] 2015-08-26 20:24
May be you need to use something like `.setFunction()` for `onConfirm` handler. Because the only way to return sync reply is to place code into bridge env, and it's impossible to change this.

**Comment by johntitus** [comment] 2015-08-27 00:10
I don't think it's supposed to return a value from the `onConfirm` handler - it's a function that is supposed to take place whenever a confirm is seen. According to the phantomjs doc I linked, returning true from it is how you click the Ok button.  The console.log part of the onConfirm handler is firing, based on the output - but the `return true` doesn't seem to be working.

**Comment by johntitus** [comment] 2015-08-27 00:11
Relevant phantomjs script:

```js
var page = require('webpage').create();

page.onConfirm = function( msg ){
    console.log('Confirm message: ' +msg);
    return true;
}
page.onLoadFinished = function(status) {
    console.log('Status ', status);
}
page.onConsoleMessage = function( msg, lineNumber, sourceId ) {
    console.log('Console: ' + msg);
}

page.open('file:///tmp/phantomconfirm/confirm.html', function(status) {
  	console.log("Status: " + status);
  	page.evaluate( function() {           
		var element = document.querySelector('a#confirm');
	    var event = document.createEvent('MouseEvent');
	    event.initEvent('click', true, true);
	    element.dispatchEvent(event);
	});
	phantom.exit();
});
```

Produces the desired/expected output:
```
Status  success
Status: success
Confirm message: OK or Cancel?
Console: You pressed OK
```

**Comment by johntitus** [comment] 2015-08-27 00:23
A bit more investigating...

I modified both the `phantomjs` and `node-phantom-simple` onConfirm handlers to look like this:

```js
page.onConfirm = function( msg ){
            console.log('Confirm message: ' + msg);
            console.log( this );
            return true;
        }
```

The `this` from `phantomjs` is 
```
[object DOMWindow]
```

The `this` from `node-phantom-simple` is
```
{ setFn: [Function],
  get: [Function],
  set: [Function],
  evaluate: [Function]
...
```
...which is the phantom object itself. Seems like the callback is firing in the wrong context.

**Comment by puzrin** [comment] 2015-08-27 01:05
I mean, event happens in `bridge.js`, and data is passed back to `node-phantom-simple.js`, to emulate event. That's ok in most cases, because event handler is never expected to return result. But that's not ok for `onConfirm`, because it works not like event, but like function call.

**Comment by johntitus** [comment] 2015-08-27 01:19
Rewritten node-phantom-simple script works:

```js
var driver = require('node-phantom-simple');

driver.create( function (err, browser) {
    browser.createPage(function (err, page) {
        page.setFn("onConfirm", function(){
            console.log('hi')
            return true;
        });
        page.onLoadFinished = function(status) {
            console.log('Status %s', status);
        }
        page.onConsoleMessage = function( msg, lineNumber, sourceId ) {
            console.log('Console: ' + msg);
        }
        page.open('file:///tmp/confirm/confirm.html', function (err,status) {
            console.log("opened site? ", status);
            page.evaluate( function() {           
                var element = document.querySelector('a#confirm');
                var event = document.createEvent('MouseEvent');
                event.initEvent('click', true, true);
                element.dispatchEvent(event);
            }, function(){
                browser.exit();
            });
        });
    });
});
```

Output
```
Status success
opened site?  success
phantom stdout: hi

Console: true
Console: boolean
Console: You pressed OK
```

**Comment by puzrin** [comment] 2015-08-27 01:23
Yeah, exactly as expected. I don't know should we add this info to readme or not (about pushing some functions to bridge namespace). That's not a bug but design limitation.

**Comment by puzrin** [comment] 2015-08-27 01:25
IDEA: we also could force default `onConfirm` handler in bridge to always return true.

**Comment by johntitus** [comment] 2015-08-27 10:21
Is there some way, under the hood, to map the onConfirm to use setFn? That way it would perform as a user would expect.

**Comment by puzrin** [comment] 2015-08-27 10:54
Possible, but dangerous IMHO. I would set "deprecation message" for `.on('onConfirm', fn)` with example how to use `setFn()`.

**Comment by johntitus** [comment] 2015-08-27 11:42
That could work. For node-horseman, I'll probably wrap it to use `setFn()`.

**Comment by puzrin** [comment] 2015-08-27 11:46
Does it worth to set default handler, emulating `OK` ? I don't know use cases for `onConfirm`.

**Comment by johntitus** [comment] 2015-08-27 11:48
I would recommend against doing that, as it may produce unexpected results for users.

**Comment by puzrin** [comment] 2015-08-27 11:49
Ok.

**Comment by puzrin** [comment] 2015-09-13 12:41
Added info to known issues. I think it's enougth.

Closing?

**Closed** 2015-09-17 04:27 UTC
