### ISSUE TITLE
Can't set user agent

### ISSUE THREAD

**Issue by billjohnston** [baudehlo/node-phantom-simple#27] opened 2014-05-27 00:55 UTC
When I set the user agent ```page.open``` hangs.

I'm setting it like this:
```
page.set('settings', {userAgent: options.userAgent});
```

**Comment by puzrin** [comment] 2015-07-08 03:21
Not a bug. You override settings with new value. Proper sequence should be:

- get settings
- modify userAgent property
- set settings back with new value

Also, #28 will be merged soon to support simplified dot-notation

**Closed by puzrin** 2015-07-08 03:21 UTC
Labels: invalid
