### ISSUE TITLE
Missing a way to create phantom callbacks

### ISSUE THREAD

**Issue by svvac** [baudehlo/node-phantom-simple#88] opened 2015-10-12 19:14 UTC
As per [PhantomJS docs](http://phantomjs.org/api/webpage/property/paper-size.html), defining a header or footer when generating a PDF requires to provide a function wrapped by `phantom.callback()` (undocumented). We can already use `page#setFn()` to assign a function, but we're still missing a way to wrap it (or maybe I missed it).

One approach would be to augment `setFn()` to allow flagging a function that should be wrapped, another would be to create a new method altogether. Any thoughts?

Cheers

**Comment by rohitghatol** [comment] 2015-10-15 16:44
You can look at this pull request and verify if that works for you https://github.com/baudehlo/node-phantom-simple/pull/86

**Comment by rohitghatol** [comment] 2015-10-15 16:45
Also this could possibly be a duplicate of https://github.com/baudehlo/node-phantom-simple/issues/78

**Comment by svvac** [comment] 2015-10-15 18:59
Well, #86 does indeed work, but it adds a tad too much magic for my taste. There already is a dedicated way to define functions in the phantom script context (using `page#setFn()`). Augmenting `set` to do the same thing seems a bit redundant and adds a whole new layer of complexity in the form of hooks. These will have to be maintained against all usecases of `phantom.callback` allowed by phantom, which increases the dependence of the lib to specific versions as new cases may arise or properties name changes.

The hooks approach can also have unexpected effects when passing a function to an option that doesn't set a processor to handle them which results in setting a string where a function is expected. That last point most likely refers  to a dev error, but can also arise, but may also apply to the case of an option with the same name but different semantics across backends (i.e. phantomjs vs slimerjs).

PR #89 works around that by explicitly using `page#setFn()` to define a function to be used by the backend. This works in the case of headers/footers because it allows deep-setting functions the same way `page#set()` does for properties (well, was *supposed* to do because that behavior was broken, see svvac/node-phantom-simple#a028fbaf for details).

**Comment by svvac** [comment] 2015-10-15 19:43
(Added an usage example in #89)

**Comment by puzrin** [comment] 2015-10-28 16:18
Advanced page props implemented in af88f55, that's enougth for the now.

**Closed by puzrin** 2015-10-28 16:18 UTC
